version: "3.5"
services:
  postgres:
    image: postgres:15
    container_name: ssps-db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    restart: always
    networks:
      - ssps

  fastify:
    image: ghcr.io/ticklabvn/ssps-be:latest
    container_name: ssps-be
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .env:/app/.env
    depends_on:
      - postgres
    restart: always
    networks:
      - ssps

volumes:
  postgres_db:

networks:
  ssps:
    name: ssps
    external: true

# run the following command after docker compose up to create seed data:
# docker-compose exec fastify npx prisma db seed
# if the ssps network haven't created yet, run the following command:
# docker network create --driver bridge ssps
