-- AlterTable
ALTER TABLE "PrintingRequest" ADD COLUMN     "printFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "serviceFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ALTER COLUMN "paid" SET DEFAULT 'not_paid';
